"""
AutoScript Compiler - FastAPI Backend Application
Exposes RESTful APIs for compilation, simulation, real execution, emergency stop, and sample code retrieval.
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional, Dict, Any, List

from backend.compiler import AutoScriptCompiler
from backend.executor.executor import Executor
from backend.ir.ir_generator import IRGenerator
from backend.parser.parser import Parser
from backend.lexer.lexer import Lexer

app = FastAPI(
    title="AutoScript Compiler API",
    description="REST API for the AutoScript Domain-Specific Automation Language Compiler",
    version="1.0.0"
)

# Enable CORS for frontend integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class CompileRequest(BaseModel):
    source: str


EXAMPLES: Dict[str, Dict[str, str]] = {
    "login.as": {
        "title": "Login Automation",
        "description": "Automates website opening, tab navigation, username/password typing, and form submission.",
        "code": """# AutoScript Login Automation Example
OPEN "https://practicetestautomation.com/practice-test-login/"
GAP 5
PRESS TAB 9
TYPE "Student"
PRESS TAB
TYPE "Password123"
PRESS ENTER"""
    },
    "loop_example.as": {
        "title": "Loop Automation",
        "description": "Demonstrates repetitive actions using the LOOP construct.",
        "code": """// AutoScript Loop Example
OPEN "https://example.com"
GAP 2

LOOP 3 {
    PRESS TAB
    GAP 1
}"""
    },
    "nested_loop.as": {
        "title": "Nested Loop",
        "description": "Demonstrates nested block parsing and execution.",
        "code": """# AutoScript Nested Loop Example
LOOP 2 {
    LOOP 3 {
        PRESS TAB
    }
}"""
    },
    "variables.as": {
        "title": "Variables Extension",
        "description": "Demonstrates SET variable declarations and symbol table tracking.",
        "code": """# Variable Declaration & Use
SET WAIT_TIME = 3
SET USER_NAME = "Student"

OPEN "https://example.com"
GAP WAIT_TIME
TYPE USER_NAME
PRESS ENTER"""
    },
    "comments.as": {
        "title": "Comments Example",
        "description": "Shows line comments with '#' and '//'.",
        "code": """# Open website
OPEN "https://example.com"

// Wait for page load
GAP 3

# Press tab twice
PRESS TAB 2"""
    },
    "invalid_syntax.as": {
        "title": "Invalid Syntax (Error Demo)",
        "description": "Demonstrates syntax error detection and caret diagnostic output.",
        "code": """OPEN
GAP
PRESS
LOOP 3 {
    PRESS TAB"""
    },
    "invalid_semantic.as": {
        "title": "Invalid Semantic (Error Demo)",
        "description": "Demonstrates semantic error detection for invalid arguments and unsupported keys.",
        "code": """GAP -5
PRESS UNKNOWN
LOOP 0 {
    PRESS TAB
}"""
    }
}


@app.get("/")
def read_root():
    return {
        "status": "online",
        "service": "AutoScript Compiler API",
        "version": "1.0.0"
    }


@app.post("/api/compile")
def compile_code(req: CompileRequest):
    compiler = AutoScriptCompiler(req.source)
    return compiler.compile()


@app.post("/api/simulate")
def simulate_code(req: CompileRequest):
    compiler = AutoScriptCompiler(req.source)
    comp_result = compiler.compile()

    if not comp_result["success"]:
        return {
            "success": False,
            "errors": comp_result["errors"],
            "logs": ["Simulation aborted due to compilation errors."]
        }

    # Reconstruct IR for simulation
    lexer = Lexer(req.source)
    tokens = lexer.tokenize()
    parser = Parser(tokens, req.source)
    ast_root, _ = parser.parse()
    ir_gen = IRGenerator(ast_root)
    ir_instructions = ir_gen.generate()

    trace = Executor.simulate(ir_instructions)
    return {
        "success": True,
        "errors": [],
        "logs": trace
    }


@app.post("/api/run")
def run_code(req: CompileRequest):
    compiler = AutoScriptCompiler(req.source)
    comp_result = compiler.compile()

    if not comp_result["success"]:
        return {
            "success": False,
            "errors": comp_result["errors"],
            "message": "Execution aborted due to compilation errors.",
            "logs": []
        }

    # Security: Only run python code generated by compiler
    generated_python = comp_result["generated_code"]
    exec_result = Executor.run_real(generated_python)
    return {
        "success": exec_result["success"],
        "message": exec_result["message"],
        "generated_code": generated_python,
        "logs": exec_result["logs"]
    }


@app.post("/api/stop")
def stop_code():
    return Executor.stop()


@app.get("/api/examples")
def get_examples():
    return EXAMPLES


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("backend.main:app", host="127.0.0.1", port=8000, reload=True)
